export const AUTH_PERMISSIONS = {
    ORGANIZATIONS_READ: 'settings.organizations.read',
    ORGANIZATIONS_CREATE: 'settings.organizations.create',
    MEMBERS_READ: 'settings.members.read',
    MEMBERS_MANAGE: 'settings.members.manage',
    USERS_READ: 'settings.users.read',
    USERS_UPDATE: 'settings.users.update',
    USERS_DELETE: 'settings.users.delete',
    BILLING_READ: 'settings.billing.read',
    BILLING_MANAGE: 'settings.billing.manage',
    REGISTRY_CUSTOMERS_READ: 'registry.customers.read',
    REGISTRY_CUSTOMERS_MANAGE: 'registry.customers.manage',
    REGISTRY_SUPPLIERS_READ: 'registry.suppliers.read',
    REGISTRY_SUPPLIERS_MANAGE: 'registry.suppliers.manage',
    HR_EMPLOYEES_READ: 'hr.employees.read',
    HR_EMPLOYEES_MANAGE: 'hr.employees.manage',
    TASKS_READ: 'tasks.tasks.read',
    TASKS_MANAGE: 'tasks.tasks.manage',
    FINANCIAL_ACCOUNTS_READ: 'financial.accounts.read',
    FINANCIAL_ACCOUNTS_MANAGE: 'financial.accounts.manage',
    FINANCIAL_CATEGORIES_READ: 'financial.categories.read',
    FINANCIAL_CATEGORIES_MANAGE: 'financial.categories.manage',
    FINANCIAL_DASHBOARD_READ: 'financial.dashboard.read',
    FINANCIAL_PAYABLES_READ: 'financial.payables.read',
    FINANCIAL_PAYABLES_MANAGE: 'financial.payables.manage',
    FINANCIAL_RECEIVABLES_READ: 'financial.receivables.read',
    FINANCIAL_RECEIVABLES_MANAGE: 'financial.receivables.manage',
    FINANCIAL_TRANSACTIONS_READ: 'financial.transactions.read',
    FINANCIAL_TRANSACTIONS_MANAGE: 'financial.transactions.manage',
} as const

export type AuthPermissionCode =
    (typeof AUTH_PERMISSIONS)[keyof typeof AUTH_PERMISSIONS]

export const DEFAULT_ORGANIZATION_ROLES = [
    {
        code: 'ADMIN',
        name: 'Administrador',
        permissions: Object.values(AUTH_PERMISSIONS),
    },
    {
        code: 'HR',
        name: 'RH',
        permissions: [
            AUTH_PERMISSIONS.ORGANIZATIONS_READ,
            AUTH_PERMISSIONS.MEMBERS_READ,
            AUTH_PERMISSIONS.MEMBERS_MANAGE,
            AUTH_PERMISSIONS.USERS_READ,
            AUTH_PERMISSIONS.HR_EMPLOYEES_READ,
            AUTH_PERMISSIONS.HR_EMPLOYEES_MANAGE,
            AUTH_PERMISSIONS.TASKS_READ,
            AUTH_PERMISSIONS.TASKS_MANAGE,
        ],
    },
    {
        code: 'FINANCIAL',
        name: 'Financeiro',
        permissions: [
            AUTH_PERMISSIONS.ORGANIZATIONS_READ,
            AUTH_PERMISSIONS.MEMBERS_READ,
            AUTH_PERMISSIONS.USERS_READ,
            AUTH_PERMISSIONS.FINANCIAL_ACCOUNTS_READ,
            AUTH_PERMISSIONS.FINANCIAL_ACCOUNTS_MANAGE,
            AUTH_PERMISSIONS.FINANCIAL_CATEGORIES_READ,
            AUTH_PERMISSIONS.FINANCIAL_CATEGORIES_MANAGE,
            AUTH_PERMISSIONS.FINANCIAL_DASHBOARD_READ,
            AUTH_PERMISSIONS.FINANCIAL_PAYABLES_READ,
            AUTH_PERMISSIONS.FINANCIAL_PAYABLES_MANAGE,
            AUTH_PERMISSIONS.FINANCIAL_RECEIVABLES_READ,
            AUTH_PERMISSIONS.FINANCIAL_RECEIVABLES_MANAGE,
            AUTH_PERMISSIONS.FINANCIAL_TRANSACTIONS_READ,
            AUTH_PERMISSIONS.FINANCIAL_TRANSACTIONS_MANAGE,
            AUTH_PERMISSIONS.REGISTRY_CUSTOMERS_READ,
            AUTH_PERMISSIONS.REGISTRY_CUSTOMERS_MANAGE,
            AUTH_PERMISSIONS.REGISTRY_SUPPLIERS_READ,
            AUTH_PERMISSIONS.REGISTRY_SUPPLIERS_MANAGE,
            AUTH_PERMISSIONS.TASKS_READ,
            AUTH_PERMISSIONS.TASKS_MANAGE,
        ],
    },
    {
        code: 'VIEWER',
        name: 'Visualizador',
        permissions: [
            AUTH_PERMISSIONS.ORGANIZATIONS_READ,
            AUTH_PERMISSIONS.MEMBERS_READ,
            AUTH_PERMISSIONS.USERS_READ,
            AUTH_PERMISSIONS.REGISTRY_CUSTOMERS_READ,
            AUTH_PERMISSIONS.REGISTRY_SUPPLIERS_READ,
            AUTH_PERMISSIONS.FINANCIAL_ACCOUNTS_READ,
            AUTH_PERMISSIONS.FINANCIAL_CATEGORIES_READ,
            AUTH_PERMISSIONS.FINANCIAL_DASHBOARD_READ,
            AUTH_PERMISSIONS.FINANCIAL_PAYABLES_READ,
            AUTH_PERMISSIONS.FINANCIAL_RECEIVABLES_READ,
            AUTH_PERMISSIONS.FINANCIAL_TRANSACTIONS_READ,
            AUTH_PERMISSIONS.TASKS_READ,
        ],
    },
] as const
