import type { LoanEntity } from '../../domain/entities/loan.entity'
import type { LoanResponseDto } from '../dto'

export function toLoanResponseDto(entity: LoanEntity): LoanResponseDto {
    return {
        id: entity.id,
        organizationId: entity.organizationId,
        borrowerType: entity.borrowerType,
        customerId: entity.customerId,
        customerName: entity.customerName,
        employeeId: entity.employeeId,
        employeeName: entity.employeeName,
        status: entity.status,
        expectedReturnDate: entity.expectedReturnDate,
        isOverdue: entity.isOverdue,
        releasedAt: entity.releasedAt?.toISOString() ?? null,
        completedAt: entity.completedAt?.toISOString() ?? null,
        canceledAt: entity.canceledAt?.toISOString() ?? null,
        notes: entity.notes,
        createdBy: entity.createdBy,
        creatorName: entity.creatorName,
        createdAt: entity.createdAt.toISOString(),
        updatedAt: entity.updatedAt.toISOString(),
        items: entity.items.map((item) => ({
            id: item.id,
            variantId: item.variantId,
            productName: item.productName,
            variantName: item.variantName,
            variantSku: item.variantSku,
            quantityReleased: item.quantityReleased,
            quantityReturned: item.quantityReturned,
            quantityLost: item.quantityLost,
            quantityDamaged: item.quantityDamaged,
            pendingQuantity: item.pendingQuantity,
            unitCostSnapshot: item.unitCostSnapshot,
            notes: item.notes,
        })),
        returns: entity.returns.map((event) => ({
            id: event.id,
            returnedAt: event.returnedAt.toISOString(),
            notes: event.notes,
            createdBy: event.createdBy,
            createdAt: event.createdAt.toISOString(),
            items: event.items,
        })),
        occurrences: entity.occurrences.map((event) => ({
            id: event.id,
            type: event.type,
            occurredAt: event.occurredAt.toISOString(),
            description: event.description,
            createdBy: event.createdBy,
            createdAt: event.createdAt.toISOString(),
            items: event.items,
        })),
        charges: entity.charges.map((charge) => ({
            id: charge.id,
            occurrenceId: charge.occurrenceId,
            financialTransactionId: charge.financialTransactionId,
            type: charge.type,
            categoryId: charge.categoryId,
            amount: charge.amount,
            dueDate: charge.dueDate,
            description: charge.description,
            canceledAt: charge.canceledAt?.toISOString() ?? null,
            createdAt: charge.createdAt.toISOString(),
        })),
    }
}
